### ISSUE TITLE
vBigDSP benchee should only be enabled if altivec headers can be found

### ISSUE THREAD

**Issue by marcusmueller** [FFTW/benchfft#10]
benchees/Makefile.am should make it conditional on ALTIVEC_CFLAGS whether vBigDSP is even included in SUBDIRS

**Comment by stevengj** [comment]
Not necessary — as explained in the README file, you should run the benchmark with `make
-k benchmark`.  This way, if any of the benchees fails to build, or crashes, or has some other problem, it will be skipped.

**Comment by stevengj** [comment]
On the other hand, we have conditional build statements for MKL etcetera and vdsp etcetera, so I guess it wouldn't hurt to do it for vbigdsp.

I think we would still include it in the SUBDIRS, but just put a conditional in vbigdsp/Makefile.am similar to https://github.com/FFTW/benchfft/blob/e349466699f2e1c13e5c00e07150e4eaa3d0bc7a/benchees/vdsp/Makefile.am

**Comment by stevengj** [comment]
[On the gripping hand](https://en.wiktionary.org/wiki/on_the_gripping_hand), if we have some other weird compiler in the future in which `-faltivec` is not needed, we still want to build vbigdsp if possible even if `ALTIVEC_CFLAGS` is empty.  Better to just rely on `make -k` here.

**Comment by marcusmueller** [comment]
Looking at it from my perspective: with `make -k`, nobody knows whether failure is *expected* or *actual failure*; I'd argue, the closer we get to not needing `-k`, the better.

**Comment by marcusmueller** [comment]
(for reference, only green-ffts-2.0 and vbigdsp fail for me now after introducing the discussed F77/legacy flags in two benchees; of these, green-ffts-2.0 is, I think, actually a bug – but I can't know!)
